site_name: 'synology'
site_description: 'Main documentation for synology'
repo_url: https://github.com/jaysuzi5/synology
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'